#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
apt-get update
apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" /usr/share/nginx/html/404.html
file="/etc/nginx/sites-available/default"
sudo chmod +w $file
cmd="error_page 404 /404.html;\nlocation = /404.html {\n usr/share/nginx/html;\n}\n"
sudo sed -i "36i $cmd" $file
sudo service nginx restart
