#!/usr/bin/env bash
#custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
file="/etc/nginx/sites-available/default"
sudo chmod +w $file
cmd1="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
sudo sed -i "37i $cmd1" $file
cmd2="error_page 404 /404.html;\nlocation = /404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sudo sed -i "37i $cmd2" $file
sudo service nginx restart
