#!/usr/bin/env bash
#custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
file="/etc/nginx/sites-available/default"
cmd2="error_page 404 /404.html;\nlocation = /404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sudo sed -i "36i $cmd2" $file
sudo service nginx restart
