#!/usr/bin/env bash
#Install nginx on your servers
apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
service nginx start
FILE="/etc/nginx/nginx.conf"
sudo sed -i "15i \\tadd_header X-Served-By $hostname;" $FILE
sudo service nginx restart
sudo service nginx reload
